const user = {
  person: {
    professionalHeadline: 'Full Stack Developer',
    completion: 0.3333,
    showPhone: false,
    created: '2020-11-06T22:01:01Z',
    verified: false,
    flags: {
      benefits: false,
      canary: false,
      enlauSource: false,
      fake: false,
      featureDiscovery: true,
      getSignaledBenefitsViewed: false,
      firstSignalSent: false,
      promoteYourselfBenefitsViewed: false,
      promoteYourselfCompleted: false,
      importingLinkedin: true,
      onBoarded: true,
      remoter: true,
      signalsFeatureDiscovery: true,
      signedInToOpportunities: true,
      importingLinkedinRecommendations: true,
      contactsImported: false,
      appContactsImported: false,
      genomeCompletionAcknowledged: true,
    },
    weight: 0,
    locale: 'en',
    subjectId: '816069',
    picture: 'https://starrgate.s3.amazonaws.com:443/users/bff01c6fd3ee64e9d135f9393b02a17001576727/profile_kUQoP2X.jpg',
    hasEmail: true,
    name: 'Kubilay Caglayan',
    links: [
      {
        id: 'pyJnlBmy',
        name: 'linkedin',
        address: 'https://www.linkedin.com/in/kubilaycaglayan',
      },
      {
        id: 'xyXZpWrM',
        name: 'gitlab',
        address: 'https://gitlab.com/kubilaycaglayan',
      },
      {
        id: 'vN8OdB2y',
        name: 'github',
        address: 'https://github.com/kubilaycaglayan',
      },
      {
        id: '0yzwpvzN',
        name: 'twitter',
        address: 'https://twitter.com/kbcaglayan',
      },
      {
        id: '9MEvlWpj',
        name: '',
        address: 'http://www.kubilaycaglayan.com',
      },
    ],
    location: {
      name: 'Ankara, Turkey',
      latitude: 39.9333635,
      longitude: 32.8597419,
      timezone: 'Europe/Istanbul',
      timezoneOffSet: 10800000,
    },
    theme: 'lightGreen500',
    id: 'WNVBKn8N',
    pictureThumbnail: 'https://starrgate.s3.amazonaws.com:443/CACHE/images/users/bff01c6fd3ee64e9d135f9393b02a17001576727/profile_kUQoP2X/a91784cf19974ffe16e3ef8486cf47b0.jpg',
    claimant: false,
    weightGraph: 'https://hcti.io/v1/image/f7a29116-6b5e-4701-a3b9-4ee3ba50d0f8',
    publicId: 'kblycaglayan',
  },
  stats: {
    strengths: 3,
    interests: 3,
  },
  strengths: [
    {
      id: '9MEmRw1M',
      code: 18319,
      name: 'Javascript',
      weight: 0,
      recommendations: 0,
      media: [],
      created: '2020-11-06T22:30:00',
    },
    {
      id: 'wM72K0xN',
      code: 50182,
      name: 'React',
      weight: 0,
      recommendations: 0,
      media: [],
      created: '2020-11-06T22:29:49',
    },
    {
      id: 'GNKJpwoy',
      code: 29411,
      name: 'Ruby on Rails',
      weight: 0,
      recommendations: 0,
      media: [],
      created: '2020-11-06T22:29:47',
    },
  ],
  interests: [
    {
      id: 'KNxKO73y',
      code: 145684,
      name: 'WebAssembly',
      media: [],
      created: '2020-11-06T22:30:14',
    },
    {
      id: 'GNK8Q0VM',
      code: 23813,
      name: 'Node.js',
      media: [],
      created: '2020-11-06T22:30:18',
    },
    {
      id: 'wM79eO3y',
      code: 50183,
      name: 'React Native',
      media: [],
      created: '2020-11-06T22:30:24',
    },
  ],
  experiences: [],
  awards: [],
  jobs: [],
  projects: [],
  publications: [],
  education: [],
  opportunities: [
    {
      id: 'y0Jn1XlM',
      interest: 'hiring',
      field: 'active',
      data: false,
    },
    {
      id: 'NV2oZY0N',
      interest: 'gigs',
      field: 'active',
      data: false,
    },
    {
      id: 'MBaqeDlN',
      interest: 'internships',
      field: 'active',
      data: false,
    },
    {
      id: 'M9gKLEwy',
      interest: 'mentoring',
      field: 'active',
      data: false,
    },
    {
      id: 'NOWY540N',
      interest: 'advising',
      field: 'active',
      data: false,
    },
    {
      id: 'ykQBdr2M',
      interest: 'industries',
      field: 'types',
      data: [
        {
          code: 33426,
          locale: 'en',
          name: 'Software Engineering',
        },
        {
          code: 33335,
          locale: 'en',
          name: 'Software Development',
        },
        {
          code: 33336,
          locale: 'en',
          name: 'Remote',
        },
      ],
    },
  ],
  languages: [
    {
      code: 'en',
      language: 'English',
    },
  ],
};

export default user;
